name: reddit
channels:
  - defaults
dependencies:
  - python=3.14.6
  - pip:
    - pandas==3.0.3
    - praw==8.0.2
    - matplotlib==3.11.0
    - pre-commit==4.6.0
    - ruff==0.15.20
    - ipykernel==7.3.0
    - openpyxl==3.1.5
    - transformers==5.13.0
    - ipywidgets==8.1.8
    - torch==2.12.1
    - torchvision==0.27.1
    - nltk==3.9.4
    - sentence_transformers==5.6.0
